from pathlib import Path
R=Path(__file__).resolve().parents[1]/'assets'
R.mkdir(exist_ok=True)
def svg(content,w=1200,h=320,dark=True):
 bg='#171a2a' if dark else '#fff8fc'; fg='#fff2fa' if dark else '#382a45'; soft='#bdb2d0' if dark else '#695e78'; panel='#25253a' if dark else '#f4e9f2'; trim='#765a86' if dark else '#c7a9cd'
 return f'''<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" viewBox="0 0 {w} {h}" role="img" aria-labelledby="title desc"><title id="title">Hazel's developer profile</title><desc id="desc">PC-98-inspired desktop artwork with a gently blinking terminal cursor and floating stars.</desc><style>text{{font-family:Consolas,'DejaVu Sans Mono',monospace}}.cursor{{animation:blink 1.2s steps(1,end) infinite}}.star{{animation:twinkle 4s ease-in-out infinite}}.star2{{animation:twinkle 5s ease-in-out 1.5s infinite}}@keyframes blink{{50%{{opacity:0}}}}@keyframes twinkle{{50%{{opacity:.25}}}}@media(prefers-reduced-motion:reduce){{.cursor,.star,.star2{{animation:none!important}}}}</style><rect width="{w}" height="{h}" rx="16" fill="{bg}"/><rect x="18" y="18" width="{w-36}" height="{h-36}" rx="10" fill="{panel}" stroke="{trim}" stroke-width="2"/><rect x="18" y="18" width="{w-36}" height="40" rx="10" fill="{trim}"/><rect x="18" y="48" width="{w-36}" height="10" fill="{trim}"/><circle cx="44" cy="38" r="7" fill="#f7b3cb"/><circle cx="67" cy="38" r="7" fill="#e9d3a6"/><circle cx="90" cy="38" r="7" fill="#a9dfcf"/><text x="115" y="43" font-size="18" fill="{bg}">HAZEL.EXE  /  PERSONAL TERMINAL</text>{content}</svg>''',fg,soft
for dark in (True,False):
 suf='dark' if dark else 'light';base,fg,soft=svg('',dark=dark)
 content=f'''<text x="70" y="112" font-size="19" fill="#e7a6ca">✦ WELCOME TO MY LITTLE CORNER OF GITHUB</text><text x="70" y="183" font-size="57" font-weight="bold" fill="{fg}">Hi, I'm Hazel~!</text><text x="70" y="225" font-size="24" fill="{soft}">.NET developer  •  AI engineer  •  OSS maker</text><text x="70" y="274" font-size="20" fill="#91cfb8">~/hazel $</text><text x="212" y="274" font-size="20" fill="{fg}">building things &amp; proving they work</text><rect class="cursor" x="681" y="255" width="12" height="23" fill="#eab2d6"/><text class="star" x="1040" y="153" font-size="45" fill="#edb4d9">✦</text><text class="star2" x="994" y="220" font-size="27" fill="#9cd2d7">✧</text><text class="star" x="1094" y="254" font-size="20" fill="#d0afe8">✦</text>'''
 (R/f'header-{suf}.svg').write_text(svg(content,dark=dark)[0].replace('><style>', '><style>'),encoding='utf-8')
 content=f'''<text x="70" y="113" font-size="21" fill="#e5a1ca">SYSTEM MESSAGE  /  THANK YOU FOR VISITING</text><text x="70" y="176" font-size="38" font-weight="bold" fill="{fg}">Make something weird &amp; wonderful.</text><text x="70" y="224" font-size="23" fill="{soft}">Take breaks. Document the bugs. Share what you learn. ♡</text><text class="star" x="1035" y="242" font-size="56" fill="#e8b4df">✿</text>'''
 (R/f'footer-{suf}.svg').write_text(svg(content,h=285,dark=dark)[0],encoding='utf-8')
print('Generated',len(list(R.glob('*.svg'))),'SVG assets')
